all:
	g++ -std=c++17 -Wall -O0 -o contar_primos contar_primos.cpp
	g++ -std=c++17 -Wall -O0 -o max_segmento max_segmento.cpp
	javac ContarPrimos.java
	javac MaxSegmento.java

clean:
	rm -f contar_primos max_segmento *.class
